version: "3.8"

services:
  bot:
    build:
      context: ./
      dockerfile: ./apps/bot/Dockerfile
    depends_on:
      - db
    env_file:
      - ./.env
    volumes:
      - logs:/app/logs

  website:
    build:
      context: ./
      dockerfile: ./apps/website/Dockerfile
    depends_on:
      - db
      - bot  # Ensure bot is running before website
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    volumes:
      - logs:/app/logs

  db:
    image: postgres:15.5-alpine
    environment:
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: enotify
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
  logs: