version: "3.8"

services:
  bot:
    build:
      context: ./
      dockerfile: ./apps/bot/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./.env
    volumes:
      - logs:/app/logs
    healthcheck:
      test: ["CMD-SHELL", "python3 /app/bot/healthcheck.py"]
      interval: 120s
      retries: 3
      start_period: 20s
      timeout: 5s

  website:
    build:
      context: ./
      dockerfile: ./apps/website/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${website_port}:8000"
    env_file:
      - ./.env
    volumes:
      - logs:/app/logs
    healthcheck:
      test: ["CMD-SHELL", "python3 /app/website/healthcheck.py"]
      interval: 60s
      retries: 4
      start_period: 20s
      timeout: 8s

  db:
    image: postgres:15.5-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./schema:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 3s
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

volumes:
  postgres-data:
  logs: